version: '3.5'
services:
  api:
    container_name: api_container
    image: ghcr.io/swipe-food/backend:latest
    env_file: dkc.env
    command: ["python3", "-m", "main.api"]
    depends_on:
      - postgres
  crawler:
    container_name: crawler_container
    image: ghcr.io/swipe-food/backend:latest
    env_file: dkc.env
    command: [ "python3", "-m", "main.crawler" ]
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: "${DOCKER_POSTGRES_DB}"
      POSTGRES_USER: "${DOCKER_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${DOCKER_POSTGRES_PASSWORD}"
      SF_DATABASE_NAME: "${SF_DATABASE_NAME}"
      SF_DATABASE_USER: "${SF_DATABASE_USER}"
      SF_DATABASE_PASSWORD: "${SF_DATABASE_PASSWORD}"
    ports:
      - "${SF_DATABASE_PORT}:${SF_DATABASE_PORT}"
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - sf_postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "7777:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "${DOCKER_PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${DOCKER_PGADMIN_DEFAULT_PASSWORD}"
    volumes:
      - sf_pgadmin:/var/lib/pgadmin
volumes:
  sf_postgres:
  sf_pgadmin: