version: '3.5'
services:
  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: "${DOCKER_POSTGRES_DB}"
      POSTGRES_USER: "${DOCKER_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${DOCKER_POSTGRES_PASSWORD}"
      SF_DATABASE_NAME: "${SF_DATABASE_NAME}"
      SF_DATABASE_USER: "${SF_DATABASE_USER}"
      SF_DATABASE_PASSWORD: "${SF_DATABASE_PASSWORD}"
    ports:
      - 5432:5432
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - sf_postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "7777:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "${DOCKER_PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${DOCKER_PGADMIN_DEFAULT_PASSWORD}"
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  sf_postgres:
  pgadmin: